### PR TITLE
Change feedback data capture

### PR DESCRIPTION
**Pull request by teneightfive**
Change the feedback wording to be more focused on what the user was looking for rather than what it missing. This also added a new field to capture about whether they feel they found what they were looking for.

Part of this change involved changing the error handling to support both fields being empty and creating a new pattern around radios/checkboxes.

### CODE REVIEW

**Comment by teneightfive** [comment]
@Demotive / @bottlerocket Have taken some of the RGP work on selection buttons but I've used the same grey from the `textarea` for the border colour for now as didn't look right when they didn't match. 

That look okay or should we swap both to the blue like RGP?

**Comment by Demotive** [comment]
re border-colour I'd stick with what works in the page now. Blue will probably look a bit weird on the yellow...?

**Comment by Demotive** [comment]
screen shot 2016-10-24 at 10 48 20

Should probably say something like...?
```
Please make sure to tell us [what you were looking for](#), and [if you found it.](#)
```

**Comment by Demotive** [comment]
screen shot 2016-10-24 at 10 52 10

Should there be a third option...? The "well sort of..." option?

**Comment by Demotive** [comment]
Also should mention the ongoing discussion around placement... Do we think the top of the page is optimal? How about just before the footer? Or right at the bottom?

Just a question really...

**Pull request merged**
