### PR TITLE
Add Hotjar tracking code

### PR DESCRIPTION
**Pull request by teneightfive**

### CODE REVIEW

**Comment by Demotive** [comment]
Does this really need to go into the head? Or can we pack it into the analytics include instead?

**Comment by teneightfive** [comment]
I was thinking the same but Kenny seems to think this needs to be in the `<head>`. It's loading the other scripts async so shouldn't hold much up.

**Comment by Demotive** [comment]
If it's loading scripts in async... then... we can put it down the bottom?

**Comment by Demotive** [comment]
Your call. I was just going for neatness etc.

**Comment by teneightfive** [comment]
>Note: We generally recommend putting the Tracking Code inside the <head> area of your site. It will still work if you place the Tracking Code at the very end but your visitor recordings may be less accurate (since we may not be able to capture the initial mouse movements and actions).

Yes, in theory it doesn't _have_ to be in the `<head>` but maybe better to see how accurate it is in the head at first and we can move and compare the stats after?

**Comment by Demotive** [comment]
👍

**Pull request merged**
