### PR TITLE
Remove two column layout in favour of 1 column component stream

### PR DESCRIPTION
**Pull request by teneightfive**
We stack our components currently based on the needs of that
symptom or condition. The use of the second column isn't consistent
with that. Therefore we're dropping back to a singular column that
also contains a max width restriction for blocks of text.

The idea of moving certain components out of their current
order based on screen width doesn't feel very consistent.

Moving forward the side column may be re-introduced but for
genuine supporting content.

### CODE REVIEW

**Comment by teneightfive** [comment]
@Demotive / @daniellemullis these are the changes based on the discussion we had around components and columns. If feels like it makes more sense in most cases. The only one where it now feels slightly more aggressive is [rashes](https://nhsbeta-pr-254.herokuapp.com/symptoms/rashes-in-babies-and-children). Not sure if we do still need to case of dropping a component to the right for certain pages like this?

**Comment by Demotive** [comment]
Agree with the thinking behind this.

On the 'rashes' example, might it be more of an overall case of reducing the 'loudness' of the emergency box a bit?

Or possibly, is the emergency box really the absolute primary piece of content? Don't know the answer to that one.

**Comment by teneightfive** [comment]
Yes, I agree that if there is a problem with how this content is stacked or displayed the issue doesn't lie within whether we have 1 or 2 columns. Especially given that the majority of users are seeing this on a mobile device which receives the stacked layout anyway. 

I think this move makes sense in terms of how we're structuring the content and components and will better highlight if there are problem for users to orientate themselves around the callouts.

**Comment by daniellemullis** [comment]
Having looked through all the pages, it is more consistent. And it will make us think harder about the ordering of content. 

I've asked Kenny for the mobile/table traffic stats for beta health.  

If 80% of people see the page in a single column, then the two column logic is flawed and we shouldn't be using it for content which belongs in the flow of the page. The extra space can be used to enhance the more complex content components on desktop (eg. image cards, do's don'ts)

It gives us more options for components spanning the full width of the page.

**Comment by tyom** [comment]
Page feedback call to action looks a bit off on a page with column.

image

**Comment by teneightfive** [comment]
@tyom Yes, doesn't work as well with this layout. Maybe it needs a way of separating it from the rest of the content if we're keeping it left aligned.

This is actually to do with #249 so will do this as a separate change after this PR as it's not directly tied to this change.

You happy with these changes other than that?

**Pull request merged**
