### PR TITLE
Ensure all in-page anchor links have tracking attribute

### PR DESCRIPTION
**Pull request by teneightfive**
We currently use a custom data attribute to track in-page anchor
links.

This was being added when using the section_nav component but gets
missed when manually adding anchor navigation to the local header.

This temporarily adds the correct attribute to the existing navigation
items but will need a better long term fix. This fix may well be applied
at the publisher/content store end.

### CODE REVIEW

**Comment by tyom** [comment]
As a simple long term solution we could just scan for internal links on the page load and automatically add those data attributes. What do you think?

**Comment by r4vi** [comment]
@tyom do you mean on client side? 

I was thinking maybe make it part of the local-header component only... then add those at render time?

**Comment by tyom** [comment]
@r4vi Analytics are client-only anyway. It's probably easier to just keep it on the client.

**Comment by r4vi** [comment]
Think it'd be easier to get the component itself to register some post-processor actions like adding analytics tags rather than selecting the component client-side (somehow?) and then adding the data attribute there. 

You'd also add in an ordering dependency, the client side code that adds the data attributes would have to run before the analytics code

**Comment by tyom** [comment]
That's true. The ordering would be an issue. Perhaps `analytics.js` should just include those automatically (currently it's skipping those) rather than rely on data attribute.

I just think it would be better to keep that logic in one place rather than spreading it across the code base.

**Comment by r4vi** [comment]
I agree (don't rely on the data attribute) if we want to track all links to anchors on the same page but @teneightfive wanted to avoid that... let's talk when he's back.

**Pull request merged**
